In [1]:
import numpy as np

    #  Dimension Array's

In [2]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
b = np.arange(14).reshape(2,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [4]:
c= np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

    # Multidimension

In [5]:
d = np.array([[2,4],[4,5]])
d

array([[2, 4],
       [4, 5]])

    # Minimum Dimension

In [6]:
e = np.array([0,1,2,3,4,5,6], ndmin=4)
e

array([[[[0, 1, 2, 3, 4, 5, 6]]]])

    # Dtype Perameters

In [7]:
f = np.array([1,2,3,4,5], dtype = complex)
f

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

    # Ndim

In [8]:
a = np.array([(2,3,4),(5,6,7)])
a.ndim

2

    # Itemsize

In [9]:
b = np.array([(1,2,3)])
b.itemsize

4

    # D-type

In [10]:
a.dtype

dtype('int32')

    # Size

In [11]:
a.size

6

    # Shape

In [12]:
a.shape

(2, 3)

    # Silicing

In [13]:
a = np.array([(1,2,3,4),(5,6,7,8)])
print(a[0:,1])

[2 6]


    # Boolean 

In [14]:
bool_arr = np.array([1, .5, 0, 'aa', ''], dtype = bool)
print(bool_arr)

[ True  True False  True False]


    # Multidimension

In [15]:
a= np.array([(2,3),(4,5),(7,8)])
a[0:2,1]

array([3, 5])

    # Linearly Spacing

In [16]:
a = np.linspace(1,7,9)
print(a)

[1.   1.75 2.5  3.25 4.   4.75 5.5  6.25 7.  ]


    # Minimum Values

In [17]:
a = np.array([39,94,57])
a.min()

39

    # Maximum Values

In [18]:
a.max()

94

    # Values Sum

In [19]:
a = np.array([192,168,255])
a.sum()

615

    # Get a Square-Root

In [20]:
np.sqrt(a)

array([13.85640646, 12.9614814 , 15.96871942])

    # Subtracting Metrix

In [21]:
x= np.array([(1,2,3),(3,4,5)])
y = np.array([(5,6,7),(6,7,8)])
x-y

array([[-4, -4, -4],
       [-3, -3, -3]])

    # ADDING Matrix

In [22]:
x+y

array([[ 6,  8, 10],
       [ 9, 11, 13]])

    # Multiply Matrix

In [23]:
x*y

array([[ 5, 12, 21],
       [18, 28, 40]])

    # Divide Matrix

In [24]:
x/y

array([[0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.57142857, 0.625     ]])

    # Vertical Stack

In [25]:
np.vstack((x,y))

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [6, 7, 8]])

     # Horizontal Stack

In [26]:
np.hstack((x,y))

array([[1, 2, 3, 5, 6, 7],
       [3, 4, 5, 6, 7, 8]])

    # Contiguous Flattened Array

In [27]:
x.ravel()

array([1, 2, 3, 3, 4, 5])

    # Odd Number Filtering

In [28]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr[arr % 2 == 1 ]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

    # Zero Array

In [29]:
arrayid = np.zeros(3)
arrayid

array([0., 0., 0.])

    # 2D Zero Matrix

In [30]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

    # Logspace Array

In [31]:
A = np.logspace(3,8,num=10,base= 1000.0, dtype=float)
A

array([1.00000000e+09, 4.64158883e+10, 2.15443469e+12, 1.00000000e+14,
       4.64158883e+15, 2.15443469e+17, 1.00000000e+19, 4.64158883e+20,
       2.15443469e+22, 1.00000000e+24])

    # Random Number Generator

In [32]:
np.random.rand(3,3)

array([[0.94444011, 0.48657673, 0.30576579],
       [0.00214064, 0.49846041, 0.77197596],
       [0.88625257, 0.93630189, 0.66179729]])

    # Random Number Generator in a Given Range

In [33]:
np.random.randint(3, size= 5)

array([1, 0, 1, 2, 1])

In [34]:
np.random.randint(30, size= (2,2))

array([[ 9,  7],
       [14, 13]])

    # Identity Matrix

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

    # Digonal Array

In [36]:
np.diag(np.arange(2,5,5))

array([[2]])

    # Numpy Indexing

In [37]:
g = np.array([1,2,3,4,5,6])
g[[2,5]]

array([3, 6])

    # Last Value

In [38]:
g[-1]

6

    # Joining and Stacking Araays

In [39]:
Arr1= np.array([[1,9,2],[1,6,8]])
Arr2 = np.array([[2,5,5],[8,4,2]])
Arr1+Arr2

array([[ 3, 14,  7],
       [ 9, 10, 10]])

In [40]:
np.hstack((Arr1,Arr2))

array([[1, 9, 2, 2, 5, 5],
       [1, 6, 8, 8, 4, 2]])

In [41]:
np.vstack((Arr1,Arr2))

array([[1, 9, 2],
       [1, 6, 8],
       [2, 5, 5],
       [8, 4, 2]])

    # Concatinating

In [42]:
np.concatenate((Arr1, Arr2))

array([[1, 9, 2],
       [1, 6, 8],
       [2, 5, 5],
       [8, 4, 2]])

    # Append Value

In [43]:
np.append(Arr1,Arr2, axis = 1)

array([[1, 9, 2, 2, 5, 5],
       [1, 6, 8, 8, 4, 2]])

    # Trignomatry

In [44]:
np.sin(Arr1)

array([[ 0.84147098,  0.41211849,  0.90929743],
       [ 0.84147098, -0.2794155 ,  0.98935825]])

In [45]:
np.cos(Arr2)

array([[-0.41614684,  0.28366219,  0.28366219],
       [-0.14550003, -0.65364362, -0.41614684]])

In [46]:
np.tan(Arr1)

array([[ 1.55740772, -0.45231566, -2.18503986],
       [ 1.55740772, -0.29100619, -6.79971146]])

In [47]:
np.log(Arr2)

array([[0.69314718, 1.60943791, 1.60943791],
       [2.07944154, 1.38629436, 0.69314718]])

In [48]:
np.exp(Arr1)

array([[2.71828183e+00, 8.10308393e+03, 7.38905610e+00],
       [2.71828183e+00, 4.03428793e+02, 2.98095799e+03]])

In [49]:
np.sqrt(Arr2)

array([[1.41421356, 2.23606798, 2.23606798],
       [2.82842712, 2.        , 1.41421356]])

In [50]:
np.power(Arr1, 5)

array([[    1, 59049,    32],
       [    1,  7776, 32768]], dtype=int32)